#!/bin/bash
set -o xtrace

# only make doc for master branch
BRANCH_NAME=$(git symbolic-ref -q HEAD)
if [ "$BRANCH_NAME" != "refs/heads/master" ]; then
	exit 0
fi

set -e

CODE_COMMIT_HASH=$(git rev-parse HEAD)
CODE_COMMIT_SUBJECT=$(git log --format=%s -n 1 $CODE_COMMIT_HASH)
TMP_DOC_DIR=$(mktemp --directory)

# actual doc generation - change this to match your own generation process
rm -rf doc/*
doxygen
# end of actual doc generation
cp -r doc/* $TMP_DOC_DIR/
git stash save --include-untracked
git checkout gh-pages
rm -rf doc/*
mv $TMP_DOC_DIR/* doc/
git add -u doc/*
git commit -a -m "AG from '$CODE_COMMIT_SUBJECT' ($CODE_COMMIT_HASH)"
git checkout master
git stash pop
rmdir $TMP_DOC_DIR
